import { Mistral } from '@mistralai/mistralai';
import { NextResponse } from "next/server";

export const maxDuration = 60; // Set max duration for serverless functions

export async function POST(request: Request) {
  try {
    const formData = await request.formData();
    const image = formData.get("image") as File;

    if (!image) {
      return NextResponse.json({ error: "No image provided" }, { status: 400 });
    }

    const mistralApiKey = process.env.MISTRAL_API_KEY;
    if (!mistralApiKey) {
      return NextResponse.json(
        { error: "Mistral API Key is missing. Please add MISTRAL_API_KEY to .env.local" },
        { status: 500 }
      );
    }

    // Initialize Mistral Client
    const mistral = new Mistral({ apiKey: mistralApiKey });

    // Convert image to base64
    const arrayBuffer = await image.arrayBuffer();
    const base64Data = Buffer.from(arrayBuffer).toString('base64');
    const imageUrl = `data:${image.type};base64,${base64Data}`;

    // Single Powerful Agent using Pixtral (Free Tier)
    const response = await mistral.chat.complete({
      model: "pixtral-12b-2409",
      responseFormat: { type: "json_object" },
      messages: [
        {
          role: "user",
          content: [
            { 
              type: "text", 
              text: `You are an elite team of expert AI environmental agents (Vision, Research, and Solution agents).
              Analyze this image and return a JSON object containing the exact following structure. Do NOT include markdown formatting or backticks outside of the JSON.
              {
                "issue": "Name of the primary environmental issue detected",
                "severityScore": 85, // Number between 0 and 100
                "severityLabel": "High", // "Low", "Medium", "High", "Critical"
                "confidence": "High", // "Low", "Medium", "High"
                "evidence": ["Visual evidence 1", "Visual evidence 2"],
                "observations": ["Detailed observation 1", "Detailed observation 2"],
                "possibleCauses": ["Real-world cause 1", "Real-world cause 2"],
                "researchFindings": ["Scientific fact 1", "Scientific fact 2"],
                "researchSources": ["Credible source name 1", "Credible source name 2"],
                "actionPlan": {
                  "individual": ["Action 1", "Action 2"],
                  "community": ["Action 1", "Action 2"],
                  "municipality": ["Action 1", "Action 2"]
                },
                "timeline": {
                  "today": ["Action to take today"],
                  "thisWeek": ["Action to take this week"],
                  "thisMonth": ["Action to take this month"],
                  "longTerm": ["Long term action"]
                },
                "impactVisualization": {
                  "currentSituation": "Description of current state",
                  "intervention": "Description of cleanup/action",
                  "potentialOutcomes": ["Qualitative outcome 1", "Qualitative outcome 2", "Qualitative outcome 3"]
                },
                "futureImpact": [
                  { "timeframe": "1 Month", "consequence": "Description of consequence if ignored for 1 month" },
                  { "timeframe": "6 Months", "consequence": "Description of consequence if ignored for 6 months" },
                  { "timeframe": "1 Year", "consequence": "Description of consequence if ignored for 1 year" }
                ]
              }`
            },
            { 
              type: "image_url", 
              imageUrl: imageUrl 
            }
          ]
        }
      ]
    });

    const content = response.choices?.[0]?.message?.content;
    const finalJsonString = typeof content === 'string' ? content : "{}";
    let finalResult;
    try {
      finalResult = JSON.parse(finalJsonString);
    } catch (e) {
      console.error("Failed to parse JSON from Mistral:", finalJsonString);
      throw new Error("Invalid JSON generated by Agent");
    }

    return NextResponse.json(finalResult);

  } catch (error: any) {
    console.error("Error analyzing image:", error);
    return NextResponse.json(
      { error: error.message || "Internal Server Error" },
      { status: 500 }
    );
  }
}
